### ISSUE TITLE
not support M1 arm64 Mac

### ISSUE THREAD

**Issue by biexiang** [progrium/macdriver#106]
not support M1 arm64 Mac

**Comment by progrium** [comment]
would you like to elaborate?

**Comment by Wawilow** [comment]
> would you like to elaborate?

I'd be happy to clarify, could you tell the current status of arm64 support? Which files need to be adapted?

**Comment by progrium** [comment]
I believe we merged something in and so its a matter of working out bugs associated with it, so please try and file a specific issue if you find anything.

**Comment by lukasschwab** [comment]
9bcf762 is working great for [my simple app](https://github.com/lukasschwab/daylight), but I initially struggled to debug because there wasn't a tagged release.

**Comment by progrium** [comment]
fyi just made a tagged release. thanks for pressing

**Comment by lukasschwab** [comment]
Thank _you_ for building/maintaining this!

**Comment by pexarkh** [comment]
@progrium thank you for moving this terrific project forward!
