### ISSUE TITLE
unavailable features in WKWebView

### ISSUE THREAD

**Issue by leozeba** [progrium/macdriver#11]
Thanks for this great project! I'm really excited about it. I have tested **wetransfer.com** and **filebin.net** in a WKWebView but was unable to open a file chooser. Is it supported yet? If not, any clues how can one implement or fix this? I'm interested in helping.

Original title:
`<input type="file"> doesn't work when using webkit WKWebView`

**Comment by progrium** [comment]
Unfortunately there are a handful of things that are not available, disabled, or not exposed with WKWebView. On top of whatever web standards Safari/Webkit doesn't support yet.

I have not actually kept track but it might be a good idea to. Another thing that doesn't work is `getUserMedia` for webcams. Lets use this issue to track and collect information as I suspect most will just have to wait for Apple and workarounds will be problem specific.

**Comment by progrium** [comment]
Can somebody start a wiki page for this so we can close this issue?
