### ISSUE TITLE
Is example code running outside main goroutine unsafe?

### ISSUE THREAD

**Issue by aidansteele** [progrium/macdriver#15]
My (very rusty) knowledge of Cocoa is that actions in the UI need to happen on the "main thread" / run loop. I assume think is why `runtime.LockOSThread()` is used in all of the examples. But it looks like the Pomodoro example has a menu item's title being changed from a different goroutine:

https://github.com/progrium/macdriver/blob/a13d2b6e51df9c8aad758af32377b128ae26078b/examples/pomodoro/main.go#L21
...
https://github.com/progrium/macdriver/blob/a13d2b6e51df9c8aad758af32377b128ae26078b/examples/pomodoro/main.go#L54

It _appears_ to be working ok. My memory (again, faulty) is that these sorts of things can appear to work ok for a while, but fail in mysterious ways as the program becomes more complex. Is there some kind of wizardry going on that makes this code ok? Or should it be happening inside the Cocoa app's run loop?

**Comment by aidansteele** [comment]
I spent a while screwing around with `NSPort`, `NSConnection`, trying to integrate go channels and the run loop and then stumbled across `core.Dispatch` - which appears to do exactly what I want (run a func on the main thread). Should setting the title instead be wrapped in `core.Dispatch(func() { ... })`?

**Comment by progrium** [comment]
I believe in this case, it's already be called from the cocoa thread. But yes if you were to work with UI objects outside of that, you'd want to do it in a dispatch.

**Comment by progrium** [comment]
Oh I can see it's happening in a goroutine spawned from the callback. Yes, it should probably be put in a dispatch.

**Comment by flexzuu** [comment]
#18 shows that there are some subtile issues when we do not pay attention to this. I will try to get a PR ready to fix the example

**Comment by aidansteele** [comment]
I've been thinking about this some more since @flexzuu linked that other issue. It's a mistake that's very easy to make and usually much harder to reproduce than the systray menu title case.

I was thinking that maybe somewhere in `Send()` we could check that the method is being invoked on the main thread - and either log a warning or panic if it's not. The issue is that we probably[1] don't want to do this unconditionally because not all ObjC code is unsafe on other threads, just some frameworks, like Cocoa. Maybe we could introduce a `threadUnsafe bool` to `object` here: https://github.com/progrium/macdriver/blob/cc510679fe062b840da7c2dfb30a2f86c3e356ad/objc/object.go#L77-L79

Then we could log the warnings only for objects with that boolean set to true? And we'd have it set for all Cocoa classes. Thoughts?

**Comment by progrium** [comment]
@aidansteele i agree its an easy mistake to make. i like that you're suggesting a logging/warning approach. i'd love to see a prototype of this. i think it's just something the programmer needs to be aware of (regardless) so i'd prioritize thinking about the best way to communicate it in documentation first.

**Comment by progrium** [comment]
thank you to @flexzuu for the PR on this!
