### ISSUE TITLE
Create list of covered classes, types, and functions.

### ISSUE THREAD

**Issue by tmc** [progrium/macdriver#150]
Similar to https://github.com/progrium/macdriver/blob/main/docs/frameworks.md, for each Framework we should maintain a list of covered classes, types, and functions.

**Comment by progrium** [comment]
Code gen should just produce a log of what it's done and what it's skipped. Cause otherwise we have the schema json files.

**Comment by tmc** [comment]
Yeah agreed.

**Comment by programmingkidx** [comment]
Would this list be in the wiki?

**Comment by progrium** [comment]
generated and kept in source, linked to from wiki most likely

**Comment by progrium** [comment]
So the frameworks list from the technologies.json endpoint is incomplete. There are like 200 frameworks. I think now that we have a 1:1 package to framework setup, link to supported frameworks, and a generated framework should cover everything in it (with exceptions that should become issues when found), we don't need to maintain specific lists of coverage. We don't have functions, but once we support functions, we'd have all the functions. So I think we just need issues for the things we don't have and not keep lists of what we do have. Cause it's ... a lot.
