### ISSUE TITLE
API_UNAVAILABLE() macro not handled

### ISSUE THREAD

**Issue by programmingkidx** [progrium/macdriver#164]
MacDriver is a project that aims to make Apple's APIs available for easy use in Go. This project also includes the goal of being able to create programs not just for Mac OS but for WatchOS, iPadOS, iPhoneOS, TVOS. Perhaps even Windows and Linux one day. With these things in mind we currently don't honor the API_UNAVAILABLE() macro. This macro specifies that a method is not available for the specified operating system. When trying to build a program using MacDriver I saw this error:

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:236:1: note: 'preservationPriorityForTag:' has been explicitly marked unavailable here
- (double)preservationPriorityForTag:(NSString *)tag API_AVAILABLE(ios(9.0), watchos(2.0), tvos(9.0)) API_UNAVAILABLE(macos);
^

I think we need to implement a system that allows the user to specify which operating system to be targeted.

**Comment by programmingkidx** [comment]
Three ways come to my mind on how to handle this:
- specify the targeted operating system in a file
- specify the targeted operating system thru a command-line option
- autodetect the targeted operating system

**Comment by progrium** [comment]
Working on it. What platform were you trying?

**Comment by programmingkidx** [comment]
I only use Mac OS right now.

**Comment by progrium** [comment]
Unnecessary now
