### ISSUE TITLE
action.Set() does not return NSButton to callback function

### ISSUE THREAD

**Issue by programmingkidx** [progrium/macdriver#168]
In Objective-C NSControl's action property is set to a method that has an argument that is usually called sender. In this callback  function the sender variable should point to the control that triggered the action to take place (just like in Objective-C). So if a NSButton triggered the action sender should be set to that NSButton. In this example program the variable sender is used to get the button's title that triggered the action:

```
package main

import (
	"fmt"
	"github.com/progrium/macdriver/helper/action"
	"github.com/progrium/macdriver/macos/appkit"
	"github.com/progrium/macdriver/objc"
)

func main() {
	app := appkit.Application_SharedApplication()
	app.SetActivationPolicy(appkit.ApplicationActivationPolicyRegular)
	app.ActivateIgnoringOtherApps(true)
	w := appkit.NewWindowWithSize(200, 200)
	w.SetTitle("Test Layout")

	// Button code
	button := appkit.NewButtonWithTitle("The Super Button")
	action.Set(button, doButton)
	w.ContentView().AddSubview(button)
	
	w.MakeKeyAndOrderFront(nil)
	w.Center()
	app.Run()
}

// The action method for button
func doButton(sender objc.IObject) {
	button := sender.(appkit.Button)
	fmt.Println("button's title:", button.Title())
}
```

What should happens is that in the doButton() method should be able to print the title of the button.
What actually happens is a panic:

```
panic: interface conversion: objc.IObject is objc.Object, not appkit.Button

goroutine 1 [running]:
main.doButton({0x1002fe588?, 0x13671f750?})
	/Users/user/desktop/test/main.go:29 +0xb0
github.com/progrium/macdriver/helper/action.callAction(0x14000028560?, 0x100179268?)
	/Users/user/Documents/golang/MacDriver/MacDriver-git/macdriver/helper/action/action_handler.go:54 +0x64
github.com/progrium/macdriver/objc/ffi._Cfunc_ffi_call0(0x1400007e600, 0x1c1c9c39c, 0x1003dc930, 0x14000013810)
	_cgo_gotypes.go:150 +0x30
github.com/progrium/macdriver/objc/ffi.Call.func1(0x1400007e600?, 0x200000001?, 0x1cd2f52f8?, {0x14000013810?, 0x200000000?, 0x1400007e600?})
	/Users/user/Documents/golang/MacDriver/MacDriver-git/macdriver/objc/ffi/ffi.go:76 +0x6c
github.com/progrium/macdriver/objc/ffi.Call(0x1400007e600, 0x14000013820?, 0x1003dc930, {0x14000013810, 0x2, 0x2})
	/Users/user/Documents/golang/MacDriver/MacDriver-git/macdriver/objc/ffi/ffi.go:76 +0x30
github.com/progrium/macdriver/objc.CallMethod[...]({0x1002fd6f8, 0x136705a80}, {0x209142be0}, {0x0, 0x0, 0x100282ae0})
	/Users/user/Documents/golang/MacDriver/MacDriver-git/macdriver/objc/class.go:279 +0x4e0
github.com/progrium/macdriver/macos/appkit.Application.Run({{{0x1002fe610?}}})
	/Users/user/Documents/golang/MacDriver/MacDriver-git/macdriver/macos/appkit/application.gen.go:178 +0x54
main.main()
	/Users/user/desktop/test/main.go:24 +0xe0
exit status 2

```

**Comment by progrium** [comment]
Instead of:
```
func doButton(sender objc.IObject) {
	button := sender.(appkit.Button)
	fmt.Println("button's title:", button.Title())
}
```
try:
```
func doButton(sender objc.Object) {
	button := appkit.MakeButton(sender.Ptr())
	fmt.Println("button's title:", button.Title())
}
```

**Comment by programmingkidx** [comment]
It does not work. 
This is the error:
./main.go:19:21: cannot use doButton (value of type func(sender objc.Object)) as action.Handler value in argument to action.Set

**Comment by programmingkidx** [comment]
This is what I came up with as a fix:

```
---
 helper/action/action_handler.go | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/helper/action/action_handler.go b/helper/action/action_handler.go
index 9bbca78..16fe3dc 100644
--- a/helper/action/action_handler.go
+++ b/helper/action/action_handler.go
@@ -39,8 +39,11 @@ func Wrap(handler Handler) (target Target, selector objc.Selector) {
 }
 
 // Set set action for an ojbc instance, if it has target and setAction method.
-func Set(instance CanSet, handler Handler) {
-	target, selector := Wrap(handler)
+func Set(instance CanSet, callbackFunc Handler) {
+	callbackWrapper := func(sender objc.IObject) {
+		callbackFunc(instance)
+	}
+	target, selector := Wrap(callbackWrapper)
 	defer target.Release()
 	objc.SetAssociatedObject(instance, objc.AssociationKey("target"), target, objc.ASSOCIATION_RETAIN)
 	instance.SetTarget(target)
-- 
2.36.1
```

**Comment by programmingkidx** [comment]
This change makes the example program work correctly.

**Comment by programmingkidx** [comment]
How it works is it creates another function that calls the callback function with the control "instance" as an argument.

**Comment by progrium** [comment]
I can see that, but this makes assumptions about what Apple is passing as the sender. It works in this case, but it is not correct. Even if it were fine, this patch doesn't remove the code it totally bypasses. I'm about to push a different fix.

**Comment by progrium** [comment]
Pull and try my suggestion.

This was the change: https://github.com/progrium/macdriver/commit/8a4a2f7078550b417d4ab1da3df3ebc1fd3b9619

**Comment by programmingkidx** [comment]
> I can see that, but this makes assumptions about what Apple is passing as the sender. It works in this case, but it is not correct. Even if it were fine, this patch doesn't remove the code it totally bypasses. I'm about to push a different fix.

Yes I assume the variable sender will be a subclass of NSControl. Do you have a situation where this is not true? 
Is action.Set() only suppose to be used with NSControl subclasses?

**Comment by programmingkidx** [comment]
> Pull and try my suggestion.
> 
> This was the change: [8a4a2f7](https://github.com/progrium/macdriver/commit/8a4a2f7078550b417d4ab1da3df3ebc1fd3b9619)

This change does make your doButton() function work now, but I don't think this is the best way to fix the problem.
Your doButton() function relies on a lot of DarwinKit code that is pretty new and undocumented. My doButton() function uses Go's type assertions which are fully documented and well known to the public. I believe using my patch would be easier for the public to use.

**Comment by progrium** [comment]
Dude. 

You can see it works with anything that implements CanSet, which is a pattern elsewhere in Apple's APIs, like I was saying a while back. If you were to assume the sender is the argument, that would break Apple APIs and make this system behave inconsistent with how the underlying system is documented. Here are the docs on this pattern, which states the sender is usually but not always the instance: 
https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Target-Action/Target-Action.html

Yes, my way is undocumented right now, but that is the way that works correctly and it will be documented as such. It can be improved (for example `appkit.ButtonFrom(sender)`) but that is a different conversation. You can't type assert a value that is not already that type and Go types don't always carry across the FFI boundary, and it especially won't work if the sender is not that instance. 

Also, a little humility when facing a system you don't fully understand goes a long way when trying to persuade people of your viewpoint.
