### ISSUE TITLE
darwinkit: run enumexport on macOS 14

### ISSUE THREAD

**Issue by progrium** [progrium/macdriver#170]
To make sure we have all possible values for generated constants and enums, we need to run our export tool on the latest version of macOS. If anybody is running macOS 14 on x86_64, it would help if you could checkout the `darwinkit` branch and run:
```
go run ./generate/tools/enumexport.go
```
Then submit a PR of the resulting changes to `./generate/modules/enums` against `darwinkit`.

**Comment by programmingkidx** [comment]
Is doing this in a virtual environment or emulator ok?

**Comment by programmingkidx** [comment]
I wanted to use some NSBezelStyle constants but I could not find them in DarwinKit. Is it because of this issue? 

Does this have to be done on x86_64? I could help if you are ok with running the command on ARM64.

**Comment by programmingkidx** [comment]
It was not NSTextFieldBezelStyle. It was actually NSBezelStyleCircular or NSBezelStylePush. I was trying to use SetBezelStyle() on a NSButton. 

Here is a link to the styles I was looking at: https://developer.apple.com/documentation/appkit/nsbezelstyle?language=objc

I used the grep command to find some of the style values but wasn't successful. I'm guessing this current issue is the problem.

**Comment by progrium** [comment]
Are you staying up to date with the darwinkit branch?

https://github.com/progrium/macdriver/blob/darwinkit/macos/appkit/enumtypes.gen.go#L685

**Comment by programmingkidx** [comment]
That worked. Thank you.

I noticed that you dropped NS from everything. I thought you were into following the standard. Why the change?

**Comment by progrium** [comment]
- Because [hsiafan/cocoa](https://github.com/hsiafan/cocoa) was already doing it
- Because the package name already prefixes, keeping them would be redundant
- Because it simplifies any other prefixing we have to do (like `I` for interfaces)
- Because it's more readable 
- Because it's more like an idiomatic Go package
- Because it's not hard to understand how it works
- Because the docs will link to the full original name
- Because it works fine
