### ISSUE TITLE
darwinkit: fix opengl example

### ISSUE THREAD

**Issue by progrium** [progrium/macdriver#172]
After [porting to DarwinKit](https://github.com/progrium/macdriver/tree/darwinkit/macos/_examples/opengl), on macOS 12 I got it to run, but it didn't render. Others on other versions reported a panic. Not sure about the panic, but at least for not rendering it probably has to do with the method call to tell the view to redraw. This method is deprecated, but I imagine should still work? 

@firelizzard18 as original author, you have thoughts?

**Comment by firelizzard18** [comment]
Unfortunately no, it's been almost two years since I looked at the project that uses this and dealing with graphics frameworks was never something I was fluent with.
