### ISSUE TITLE
darwinkit: improve objc package API

### ISSUE THREAD

**Issue by progrium** [progrium/macdriver#173]
While the new objc package is better in terms of completeness and approach using FFI, the API is not quite as good as our original objc package. This issue is to improve the DX, tweak the API to match a little more closely to the old API, and maybe support old features like subclassing via struct tags.

**Comment by programmingkidx** [comment]
Two suggestions that come to mind are:
1. Comment every method. 
- Describe all the input parameters
- Describe all the output values
- Describe the purpose of the method.

2. Create a documentation page describing the objc package. Have it include:
- Small example programs that demonstrates a feature
- An overview of how the objc package works
- Descriptions of use-cases for certain methods

**Comment by progrium** [comment]
Not everything is intended to be used directly, but everything that is is now documented well enough. But the main thing was improving the API, which other than supporting the old struct tag method of subclassing, we have in a pretty good state now.
