### ISSUE TITLE
Related project: c_ocoa

### ISSUE THREAD

**Issue by cweagans** [progrium/macdriver#215]
https://felixk15.github.io/posts/c_ocoa/
https://github.com/FelixK15/c_ocoa

Not sure if you've run into any problems generating API bindings, but that project might have some useful stuff to reference!

**Comment by progrium** [comment]
Thanks. They use libobjc reflection, which is not a bad idea for C where you'll already have direct access to functions, structs, constants, etc and so you don't need to generate anything for them. However, it will be missing any documentation or links to documentation, but if you're generating just what you need, presumably you already know. We have to also map the Objective-C OOP to Go OOP and integrate both memory management systems and do more type conversion. 

Tbh, this project might have some useful stuff for them to reference, but for C its probably fine what they've got.

**Comment by programmingkidx** [comment]
@cweagans Thank you very much for sharing. I always hoped there was something like this project but for the C language.
