### ISSUE TITLE
NSApp_WithDidLaunch callback passes wrong object

### ISSUE THREAD

**Issue by TotallyGamerJet** [progrium/macdriver#22]
The function NSApp_WithDidLaunch takes a callback that is supposed to pass the notification object. But since the first thing sent to any objective-c function is the pointer to the "self" object, the wrong object is passed to the callback. Therefore calling any of the notification methods on it causes an unrecognizable selector exception.
Reproducible code:

      package main

      import (
	      "fmt"
	      "github.com/progrium/macdriver/cocoa"
	      "github.com/progrium/macdriver/core"
	      "github.com/progrium/macdriver/objc"
	      "runtime"
      )
      
      func main() {
	      runtime.LockOSThread()
	      pool := core.NSAutoreleasePool_New()
	      defer pool.Release()
	      var window cocoa.NSWindow
	      app := cocoa.NSApp_WithDidLaunch(func(notification objc.Object) {
		      fmt.Println(notification.Get("name").String())
		      // create a reference rect
		      contentSize := core.NSMakeRect(0, 0, 800, 600)
      
		      // allocate window
		      window = cocoa.NSWindow_Init(contentSize, cocoa.NSTitledWindowMask, cocoa.NSBackingStoreBuffered, true)
      
		      // allocate view
		      window.MakeKeyAndOrderFront(window)
	      })
	      app.SetActivationPolicy(cocoa.NSApplicationActivationPolicyRegular)
	      app.ActivateIgnoringOtherApps(true)
	      app.Run()
     }

This is the error:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DefaultDelegate name]: unrecognized selector sent to instance 0x450a3c0'`

The solution is to either change the callback function signature to accommodate the "self" object or wrap the callback in another function so it works properly. I prefer the second option which would look something like this.
cocoa/NSApplication.go
```
func NSApp_WithDidLaunch(cb func(notification objc.Object)) NSApplication {
	DefaultDelegateClass.AddMethod("applicationDidFinishLaunching:", func(_, notification objc.Object) {
              cb(notification)
        })
	app := NSApp()
	app.SetDelegate(DefaultDelegate)
	return app
}
```

**Comment by progrium** [comment]
glad this was caught and thanks for the PR.
