### ISSUE TITLE
APFS (Case-sensitive) filesystem protocols.gen.m:3:9: fatal error:: 'Appkit/Appkit.h' file not found

### ISSUE THREAD

**Issue by ka1i** [progrium/macdriver#238]
When I try to run example `largetext` with preview package version.

*Package Version: github.com/progrium/macdriver v0.5.0-preview*
```zsh
# github.com/progrium/macdriver/macos/appkit
protocols.gen.m:3:9: fatal error: 'Appkit/Appkit.h' file not found
```

Env:
+ ARM64 CPU
+ macOS 14.2.1
+ APFS (Case-sensitive)

if change source code, like 'Appkit/Appkit.h' -> 'AppKit/AppKit.h', it can be working.

**Comment by progrium** [comment]
thanks! should be fixed in main
