### ISSUE TITLE
user-agent?

### ISSUE THREAD

**Issue by RRancio** [progrium/macdriver#252]
i was looking at the examples on the repo, and tried some ways to add a "user-agent" header, but i wasn't able, does this feature exists on this API?

![image](https://github.com/progrium/macdriver/assets/80014347/33aab744-4e59-4ba6-a083-fd0d91e89805)

(ignore the malformed url)

**Comment by progrium** [comment]
The webview (`wv`) should have a `customUserAgent` property. Did you try `wv.SetCustomUserAgent("My user agent")`?

**Comment by progrium** [comment]
Hope this helped.
