### ISSUE TITLE
Can not create Event Taps

### ISSUE THREAD

**Issue by tlindsay** [progrium/macdriver#253]
I'm sure I'm missing something here–I'm new to Mac development. But I tried for several hours last night, and couldn't come up with a way to create an event tap. I don't see the [`CGEventTapCreate`](https://developer.apple.com/documentation/coregraphics/1454426-cgeventtapcreate?language=objc) function anywhere in the documentation. Am I meant to `import "C"` to accomplish something like this?

I tried doing something like `objc.Call[corefoundation.MachPortRef](...)`, but couldn't figure out a valid handle to give, and everything I tried panicked because the handle was `nil`.

I am using the `0.5.0-preview`, so maybe the functions I need just haven't landed yet? I was just confused because all of the supporting constants/types (i.e., `EventTapLocation`, `EventTapOptions`, etc.) do exist.

**Comment by progrium** [comment]
We don't create function bindings yet, but yes you can use CGO in the meantime.

**Comment by tlindsay** [comment]
👍 Got it. Thanks for the reply!
