### ISSUE TITLE
Methods with pointer to pointer arguments using old signature

### ISSUE THREAD

**Issue by programmingkidx** [progrium/macdriver#255]
A commit was made to better support pointer to pointer arguments. This is commit https://github.com/progrium/macdriver/commit/6a98f82290e53bc5d82cb59436644f705156d7cb. Running 'go generate ./macos/appkit' would update all the methods in a selected folder to use the new function signature. 

Example: 
// Before running 'go generate ./macos/appkit'
func (n_ Nib) InstantiateWithOwnerTopLevelObjects(owner objc.IObject, topLevelObjects []objc.IObject) bool {

// After running 'go generate ./macos/appkit'
func (n_ Nib) InstantiateWithOwnerTopLevelObjects(owner objc.IObject, topLevelObjects unsafe.Pointer) bool {

The '[]objc.IObject' type is replaced with an 'unsafe.Pointer' type. 

I ask that the Macdriver repo have all its supported frameworks updated by running 'go generate ./macos/framework-name-here' 

Thank you.

**Comment by progrium** [comment]
Or is this fine? I will run generate soon either way.

**Comment by progrium** [comment]
This touched a lot, but it's in. All examples are working. Let me know if it's what you expected so I can make any fixes before finally releasing 0.5.0 ... thanks for all your help @programmingkidx
