### ISSUE TITLE
Menu bar widget example dies when a window is put into full-screen

### ISSUE THREAD

**Issue by cschneider4711** [progrium/macdriver#26]
Cool project, thx for creating it!

Just a quick info: The Pomodoro menu bar widget vanishes (process dies) as soon as any unrelated application's window is put into full screen. MacOS 11.2.2

**Comment by progrium** [comment]
can you record this bug with https://recordit.co/ or something? thanks!

**Comment by cschneider4711** [comment]
Yep, just verified it with macOS 11.2.3

Attached a GIF (dithered and low-res to be small enough) of how it is observed.
![Screen Recording 2021-03-09 at 14 10 03](https://user-images.githubusercontent.com/6897328/110476669-86f37b00-80e2-11eb-8f6f-8363d8efbfbd.gif)

**Comment by progrium** [comment]
awesome, thank you.

**Comment by progrium** [comment]
I have not had time to reproduce, can others? Anybody have ideas on what this could be?

**Comment by matoous** [comment]
I was able to reproduce the issue. No idea what the issue is yet though.

**Comment by flexzuu** [comment]
Can you try it again maybe #30 fixed this too?

**Comment by bigemon** [comment]
> Can you try it again maybe #80 fixed this too?

It's working !

B. Macbook Pro 2017 (Intel / Big Sur 11.4 / amd64 )            -   test passed
C. Macbook Air 2020 (M1 / Big Sur 11.6 / amd64 with Rosetta )    -  test passed

I think this problem has been completely solved.

![图像2021-11-1 00 26](https://user-images.githubusercontent.com/3683548/139593664-0e4aa8d9-fb42-46df-9a11-e7bec184441e.jpg)
<img width="873" alt="截屏2021-11-01 00 28 26" src="https://user-images.githubusercontent.com/3683548/139593701-f3246d0b-2d97-48a8-b239-b20acfbeaee6.png">
