### ISSUE TITLE
"new repo" link on 0.1.0 release points to the wrong place

### ISSUE THREAD

**Issue by cweagans** [progrium/macdriver#47]
Currently, the link on [the release page](https://github.com/progrium/macdriver/releases/tag/v0.1.0) points to https://github.com/progrium/macdriver/blob/v0.1.0/github.com/progrium/macbridge

Should point to https://github.com/progrium/macdriver/blob/v0.1.0/github.com/progrium/macbridge

**Comment by progrium** [comment]
Thanks! Actually it should have pointed to http://github.com/progrium/macbridge .. fixed!

**Comment by cweagans** [comment]
Ah, yes. That's what I get for opening issues early in the morning :) thanks!
