### ISSUE TITLE
Do I have to know cocoa to use this library?

### ISSUE THREAD

**Issue by whimthen** [progrium/macdriver#54]
How to add some components on the window?  Such as input boxes, tables, file selectors and so on.  Or can more documents be added?

**Comment by progrium** [comment]
Yes you have to know how to use Cocoa and you have to use Apple documentation to get the most out of this. I don't know what you mean by more documents, but with the core Objective-C bindings you can do nearly anything you can do in Objective-C.

**Comment by whimthen** [comment]
> Yes you have to know how to use Cocoa and you have to use Apple documentation to get the most out of this. I don't know what you mean by more documents, but with the core Objective-C bindings you can do nearly anything you can do in Objective-C. 

Thanks for the reply, the above document is not appropriate, it refers more to some examples, because I have not used Objective-C.
Thanks again.
