### ISSUE TITLE
Play sounds using NSSound

### ISSUE THREAD

**Issue by yummyweb** [progrium/macdriver#64]
Use `NSSound` to play audio files.

Reference: https://developer.apple.com/documentation/appkit/nssound?language=objc

**Comment by progrium** [comment]
that would be a great addition, are you interested in providing a wrapper for it until we can generate it?

**Comment by yummyweb** [comment]
Ok, is there some sort of style in which I should write the code and is NSSound part of the macdriver Objc framework?

**Comment by yummyweb** [comment]
Closing this issue as it is fixed with #82
