### ISSUE TITLE
fatal error: 'objc/runtime.h' file not found

### ISSUE THREAD

**Issue by cmacrae** [progrium/macdriver#8]
Hey @progrium 👋 

Thank you so much for macdriver, you have no idea how excited I am about this 🙌 

I feel a bit silly not even being able to get going on the `largetype` example, but I get:
```
# github.com/progrium/macdriver/objc
../../../../go/pkg/mod/github.com/progrium/macdriver@v0.0.1/objc/class.go:10:10: fatal error: 'objc/runtime.h' file not found
#include <objc/runtime.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
 ```

When I try to `go run *.go` with `main.go` containing the example's contents.  
I've set up with the usual `go mod init ...` and `go mod download`.  
Tried `go get -u` and `CGO_ENABLED=1 go run *.go` just in case, but it's the same results.

I'm sure it's just something dead simple that I'm missing 😅

**Comment by progrium** [comment]
Ah, I might be missing some pre-req steps. Quick question, how did you install go? What version of OS X? Do you have Xcode Command Line Tools installed?

**Comment by cmacrae** [comment]
I have `go1.15.6 darwin/amd64` installed from [nixpkgs](https://github.com/NixOS/nixpkgs) on macOS 11.1  
I don't have the Xcode Command Line Tools installed as the utilities provided in that package are present in my environment via nixpkgs too :)

Is there something specific in that package that's needed for those headers?

**Comment by progrium** [comment]
The headers.

**Comment by progrium** [comment]
I think I saw them under an SDK directory, googling "apple headers sdk nix" I found there is maybe a nix package called "apple-sdk" and [this looks similar](https://discourse.nixos.org/t/fatal-error-os-availability-h-file-not-found/5331) but I'm no nix expert! Hope that's helpful, pls share what you find

**Comment by cmacrae** [comment]
>Is there something specific in that package that's needed for those headers?

>The headers.

That made me chuckle, haha.

Great, thank you for the help on this! It was indeed just headers/libraries missing from my system.  

For anyone coming across this with a conventional set-up, I believe you need to install the Xcode Command Line Tools (as @progrium suggests above).  

If you're like me and you're running Nix, the following `shell.nix` will give you a build environment (and of course this is enough to go off to build a package):
```nix
with import <nixpkgs> {};
stdenv.mkDerivation rec {
  name = "example";
  env = buildEnv { name = name; paths = buildInputs; };

  buildInputs = [
    go
    clang

    darwin.apple_sdk.frameworks.AppKit
    darwin.apple_sdk.frameworks.Cocoa
    darwin.apple_sdk.frameworks.CoreFoundation
    darwin.apple_sdk.frameworks.WebKit
  ];

  CPATH = "${darwin.Libsystem}/include";
  NIX_LDFLAGS = "-framework AppKit -framework Cocoa -framework CoreFoundation -framework WebKit";
}
```

Then something like `nix-shell --pure --command "go run *.go Nix\!"` works 🎉 

Thanks again @progrium - I can't wait to get started building stuff with this 🙇
