### ISSUE TITLE
Todo for the project

### ISSUE THREAD

**Issue by yummyweb** [progrium/macdriver#83]
It would be great if a contributing guide or a todo for the project is created to support individuals interested in the project.

**Comment by progrium** [comment]
Would love to, but don't know what to include. Since you've been through it, what would it include? Give me an outline.

**Comment by yummyweb** [comment]
Personally, I would include the components yet to add like NSTextField (Wanted to work on that) and other such components. Along with Apple Technologies like AVFoundation. I would also suggest you to add the wiki link on types on the README.md since it is quite hard to find, from personal experience.

**Comment by progrium** [comment]
Nearly every symbol would be added to the list. That's a lot of symbols to have in a todo/list. We're still not even able to support every API, so we're taking a "generate bindings as needed/desired" since you can do *most* things with the core `objc` package.
