### ISSUE TITLE
How to use printOperationWithPrintInfo with webkit framework ?

### ISSUE THREAD

**Issue by sipian** [progrium/macdriver#86]
I want to use webkit framework to load a URL, and using `printOperationWithPrintInfo`, on button click, I want to show dialog box to print the webpage.

I am new to macOS development and am building a macOS app in golang using `macdriver`.

I have followed [examples/topframe](https://github.com/progrium/macdriver/blob/main/examples/_topframe/main.go#L1) to launch WKWebView to show my URL. `printOperationWithPrintInfo` is mentioned in [macdriver/api/webkit/wkwebview.objc.json](https://github.com/progrium/macdriver/blob/a9ab20f36de27d6d6c3a10c8520ded6e311e1bcd/api/webkit/wkwebview.objc.json#L679) but I am not getting how to proceed further to connect `printOperationWithPrintInfo` with it.

There is limited documentation online and would appreciate some direction on how to proceed.

**Comment by progrium** [comment]
I think it's because it's not part of the main interface of WKWebView so we probably don't generate bindings for it (yet). You can use `Send` to call it without bindings until we support these kinds of methods in binding generation.
