### ISSUE TITLE
Package up as a Mac App? 

### ISSUE THREAD

**Issue by matthewmueller** [progrium/macdriver#97]
Hey, this project is super cool. I was wondering how difficult it would be to turn the built binary into a `.dmg` or put in the App Store? 

I tried https://github.com/sindresorhus/create-dmg, but it has certain expectations about the build:

```
Error: ENOTDIR: not a directory, open 'main/Contents/Info.plist'
```

**Comment by progrium** [comment]
you just need a plist and make an app bundle. but you also have to deal with signing and notarizing. and entitlements.

**Comment by matthewmueller** [comment]
Got it! If I get it working with MacDriver, I'll write an update here.
