### ISSUE TITLE
The API I want is not in cocoa, is it possible to add this example

### ISSUE THREAD

**Issue by wushu037** [progrium/macdriver#98]
For example, I want to call [GCController.controllers](https://developer.apple.com/documentation/gamecontroller/gccontroller/1458871-controllers)

I don't know the mechanism of macdriver (is it called using reflection?) I also don't know about objective-c, so I would like to get a more detailed example

**Comment by progrium** [comment]
In general, you can get top level symbols with `objc.Get` and then call `Send` on them. Arguments and return values have to be converted but there are helpers for that.
