### ISSUE TITLE
Missing NSApplicationMain() implementation

### ISSUE THREAD

**Issue by iMacker2020** [progrium/macdriver#99]
In an Objective-C application the NSApplicationMain() function is called to start the application. It basically does all this:

void NSApplicationMain(int argc, char *argv[]) {
    [NSApplication sharedApplication];
    [NSBundle loadNibNamed:@"myMain" owner:NSApp];
    [NSApp run];
}
*from https://developer.apple.com/documentation/appkit/nsapplication?language=objc

Please add this function to the Go bindings. This would enable the use of xib files. 

Thank you.

**Comment by progrium** [comment]
It's not clear what you want added.
